name: KCHelper
main: com.doreoom.kcHelper.Main
version: 1.4
commands:
  v:
    description: 一键隐身！
    usage: /v 1
  mt:
    description: 维护功能开关！
    usage: /mt 1
  nt:
    description: 管理提示开关！
    usage: /nt 1
  ab:
    description: 死亡自动ban！
    usage: /ab 1
  bt:
    description: ban talk!
    usage: /bt 1
  ks:
    description: 玩家死亡显示开关
    usage: /ks 1plugin.getConfig().getConfigurationSection("deadshow");